spring:
  application:
    name: business-microservice01-product
  cloud:
    config:
      uri: http://localhost:8081
      username: root
      password: s3cr3t
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka